newsletter_poc:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: wjb34325
      user: DEVRAJ_GURJAR
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: COMMON_TENANT_DEV
      schema: DBT_UDL
      threads: 4
